CREATE TABLE IF NOT EXISTS AUTHOR(ID BIGSERIAL PRIMARY KEY,
                                  NAME VARCHAR(255) UNIQUE);

CREATE TABLE IF NOT EXISTS GENRE(ID BIGSERIAL PRIMARY KEY,
                                 NAME VARCHAR(255) UNIQUE);

CREATE TABLE IF NOT EXISTS BOOK(ID BIGSERIAL PRIMARY KEY,
                                NAME VARCHAR(255),
                                AUTHOR_ID BIGINT,
                                GENRE_ID BIGINT,
                                CONSTRAINT AUTHOR_BOOK_FK FOREIGN KEY(AUTHOR_ID) REFERENCES AUTHOR,
                                CONSTRAINT GENRE_BOOK_FK FOREIGN KEY(GENRE_ID) REFERENCES GENRE);