spring:
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: never

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: false

    show-sql: true

  sql:
    init:
      mode: always
      schema-locations: schema.sql

  main:
    allow-circular-references: true
